[package]
name = "system_viewer"
version = "0.1.0"
authors = ["Daniel Coelho"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_log = "0.2"
console_error_panic_hook = "=0.1.5"
js-sys = "0.3.19"
log = "0.4"
lazy_static = "1.3.0"
wasm-bindgen = "0.2.44"
instant = { version = "0.1", features = [ "wasm-bindgen", "now" ] }
wasm-bindgen-futures = "0.4"
winit = { version = "0.22", features = ["web-sys"] }
egui = "0.5.0"
gui_backend = { path = "gui_backend" }
gltf = "0.15.2"
nalgebra = "0.23.2"
image = "0.23.12"
regex = "1.4.2"

[dependencies.web-sys]
version = "0.3.44"
features = [
  'console',
  'CssStyleDeclaration',
  'Document',
  'DomRect',
  'Blob',
  'Element',
  'FileReader',
  'HtmlInputElement',
  'File',
  'HtmlCanvasElement',
  'FileList',
  'HtmlElement',
  'KeyboardEvent',
  'Location',
  'MouseEvent',
  'Performance',
  'Storage',
  'Touch',
  'TouchEvent',
  'TouchList',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGl2RenderingContext',
  'WebGlShader',
  'WebGlTexture',
  'WebGlUniformLocation',
  'WebGlVertexArrayObject',
  'WheelEvent',
  'Window',
]

[build-dependencies]
wasm-pack = "0.9.1"

[profile.release]
opt-level = "s"

[profile.dev.package."*"]
opt-level = 3