use std::{cell::RefCell, collections::HashMap};

thread_local! {
    pub static ASSET_MANIFEST: RefCell<HashMap<&'static str, &'static str>> = {
        let manifest = RefCell::new(HashMap::new());
        {
            let mut manifest = manifest.borrow_mut();
            include!(concat!(env!("OUT_DIR"), "/autogenerated_manifest.rs"));
        }
        return manifest;
    };
}
